### ISSUE TITLE
ValueError: pyDes can only work with encoded strings, not Unicode.

### ISSUE THREAD

**Issue by hktalent** [toddw-as/pyDes#11]
```
text = r'一对一异或操作，得到结果,其中,"ord(char)"得到该字符对应的ASCII码,"chr(int)"刚好相反'
cipher_text = Des2.des_encrypt(text)
print(cipher_text)
text = Des2.des_descrypt(cipher_text)
print(text)
```
Traceback (most recent call last):
    cipher_text = Des2.des_encrypt(text)
  File "/Des2.py", line 19, in des_encrypt
    en = k.encrypt(s, padmode=PAD_PKCS5)
  File "/usr/local/lib/python3.7/site-packages/pyDes.py", line 655, in encrypt
    data = self._guardAgainstUnicode(data)
  File "/usr/local/lib/python3.7/site-packages/pyDes.py", line 241, in _guardAgainstUnicode
    raise ValueError("pyDes can only work with encoded strings, not Unicode.")
ValueError: pyDes can only work with encoded strings, not Unicode.

**Comment by EnhboldH** [comment]
print ("%r" %cipher_text)

**Comment by twhiteman** [comment]
The r'...' produces a (unicode) string in Python3.

When using Python3 - you would need to convert to bytes to pass into pyDes - example:
```python
$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import pyDes
>>> key = '01234567'
>>> d = pyDes.des('01234567', padmode=pyDes.PAD_PKCS5)
>>> text = r'一对一异或操作，得到结果,其中,"ord(char)"得到该字符对应的ASCII码,"chr(int)"刚好相反'

>>> d.encrypt(text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/toddw/.local/lib/python3.8/site-packages/pyDes.py", line 655, in encrypt
    data = self._guardAgainstUnicode(data)
  File "/home/toddw/.local/lib/python3.8/site-packages/pyDes.py", line 241, in _guardAgainstUnicode
    raise ValueError("pyDes can only work with encoded strings, not Unicode.")
ValueError: pyDes can only work with encoded strings, not Unicode.

>>> type(text)
<class 'str'>
>>> print ('%r' % (text, ))
'一对一异或操作，得到结果,其中,"ord(char)"得到该字符对应的ASCII码,"chr(int)"刚好相反'

>>> d.encrypt(bytes(text, 'utf-8'))
b'\x05\x8b9\xad\xa8\xaa5Y\x15Q\x8b\xfd\x97O\xa8\xed\xa9\x9dz\x0c\xbe\xbc\x12\x8b\xb7\x89\x13\x9b/,\x85\xa2[^\x9e%w\n<_\xa7\xe9{\x81#\xbb\tt\x96\x94\x84ip&\xde[\xab9\xdeP/\x94\xc7\xe6\xe0\x14W)\x85-\xf8Q\x19G\x92q\xe4^wq\x93\xeb\xe1\x9c\x0c\x1a\xf9\x07\xeb\xea\x82\xd0\x9a\xad\xa7\x0e/\xb3\xa765,\xf6\xf7\x1a\xeef\xca\x88\x8a\x91P'
```
